apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-renewal-agent
  namespace: cert-manager
  labels:
    app: cert-renewal-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-renewal-agent
  template:
    metadata:
      labels:
        app: cert-renewal-agent
    spec:
      automountServiceAccountToken: true
      serviceAccountName: cert-renewal-agent 
      containers:
      - name: cert-renewal-agent
        image: nicolaka/netshoot
        command: ["bash", "/opt/scripts/delete-failed-cert-requests.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - "ALL"
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        volumeMounts:
          - name: scripts
            mountPath: /opt/scripts
      volumes:
        - name: scripts
          configMap:
            name: cert-renewal-agent-scripts
