apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foo-tls
  namespace: cert-manager
spec:
  dnsNames:
  - foo.bar.svc.cluster.local
  duration: 1m
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 24h0m0s
  secretName: foo-tls
  usages:
  - server auth
